FROM python:3.10

RUN apt-get update -y
RUN	apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	python3-setuptools \
	libsodium23 && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY pyproject.toml ./
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

ADD . .

ENTRYPOINT ["/bin/bash", "-c", "pytest \"$@\"", "--"]